"use client";
import { createContext, useContext, useState, useEffect, ReactNode } from "react";

const translations: Record<string, Record<string, Record<string, string>>> = {
  en: {
    nav: { features: "Features", faqs: "FAQs", newsletter: "Newsletter", community: "Community", blog: "Blog", scheduleDemo: "Schedule Demo", signUp: "Sign Up", login: "Login" },
    hero: { title: "Transform Your Finances with AI Power!", description: "Revolutionize your finances with our AI-powered app. Effortlessly track expenses, optimize investments, and reach your goals all in one place.", subscribe: "Subscribe now", emailPlaceholder: "Enter your email", notice: "Sign up to Finquanta AI newsletter for all the latest news, trends and insights from our industry experts." },
    features: { banner: "Optimizing financial decisions through powerful AI technology.", title: "Our AI assistant focuses on what matters most", tagline: "delivering smart financial strategies for your business.", maturity: "Maturity", maturityDesc: "Smart strategies for every stage, from startup to growth.", nature: "Nature", natureDesc: "Industry-specific insights to help you make better decisions.", niche: "Niche", nicheDesc: "Financial guidance based on your business model and operations.", financialHealth: "Financial Health", financialHealthDesc: "Stay on top of your business cash flow, expenses, and profits." },
    faq: { title: "Frequently Asked Questions", q1: "How much does Finquanta AI cost?", a1: "We offer a free plan with essential tools, plus paid plans starting at $49.99/month.", q2: "How does Finquanta AI work?", a2: "Our AI analyzes your business finances and provides smart recommendations.", q3: "What are the benefits of using Finquanta AI?", a3: "Save time, make smarter financial decisions, and get AI-powered insights." },
    newsletter: { title: "Stay in the know", description: "Sign up to Finquanta AI newsletter for all the latest news, trends and insights from our industry experts.", emailPlaceholder: "Enter your email", subscribe: "Subscribe now" },
    community: { title: "You can also connect with us on" },
    footer: { terms: "terms of service", privacy: "privacy notice", aiRisk: "ai risk disclosure" },
    legal: { returnHome: "Return to Home Page", termsTitle: "FINQUANTA TERMS OF SERVICE", termsIntro: "These Terms of Service govern your access to and use of the Finquanta platform. By creating an account or using the platform, you agree to be bound by these terms.", privacyTitle: "FINQUANTA PRIVACY NOTE", privacyIntro: "Finquanta is committed to protecting the privacy and security of the business and financial information entrusted to us by our users.", aiRiskTitle: "FINQUANTA AI RISK DISCLOSURE", aiRiskIntro: "Finquanta uses artificial intelligence, machine learning models, and automated systems to help businesses manage financial data, automate bookkeeping processes, and generate financial insights." },
    auth: { login: "Login", signUp: "Sign Up", email: "Email", password: "Password", confirmPassword: "Confirm Password", forgotPassword: "Forgot Password?", rememberMe: "Remember Me", loginButton: "Login", signUpButton: "Create Account", alreadyHaveAccount: "Already have an account?", dontHaveAccount: "Don't have an account?", loginWithGoogle: "Login with Google", signUpWithGoogle: "Sign Up with Google", resetPassword: "Reset your password", resetPasswordDesc: "Enter your email and we'll send you a reset link.", sendResetLink: "Send Reset Link", backToSignIn: "Back to Sign In", checkEmail: "Check your email", resetLinkSent: "We sent a password reset link to" },
    dashboard: { title: "Dashboard", profileSettings: "Profile Settings", termsOfService: "Terms of Service", privacyPolicy: "Privacy Policy", search: "Search", balance: "Balance", cashflow: "Cashflow", expense: "Expense", bookkeeping: "Bookkeeping", last30Days: "Last 30 days", addData: "Add Data", date: "Date", type: "Type", detail: "Detail", price: "Price", amount: "Amount", noTransactions: "No transactions yet", totalRevenue: "Total Revenue", noDataYet: "No data yet", goals: "Goals", addGoal: "Add Goal", noGoalsAdded: "No goals added yet", bankAccount: "Bank account", light: "Light", dark: "Dark", version: "Version" },
    settings: {
      languageSettings: "Language Settings",
      displayLanguage: "Display Language",
      changeLanguageAcrossSite: "This will change the language across the entire site.",
      notificationSettings: "Notification Settings",
      selectNotificationPreference: "Select your notification preference",
      giveFeedback: "Give Feedback",
      logOut: "Log Out",
      deleteAccount: "Delete account",
      deleteAccountWarning: "Closing your account can't be undone. Please make sure your account balance is $0.00 before you begin.",
      deleteAccountNow: "Delete Account Now",
      languageRegion: "Language & Region",
      configureLanguageSettings: "Configure your preferred language, timezone, and regional settings",
      timeZone: "Time Zone",
      selectTimezone: "Select timezone",
      currentTime: "Current time:",
      dateFormat: "Date Format",
      today: "Today:",
      timeFormat: "Time Format",
      twelveHour: "12-hour (AM/PM)",
      twentyFourHour: "24-hour",
      currency: "Currency",
      example: "Example:",
      measurementSystem: "Measurement System",
      metric: "Metric (kg, cm, L)",
      imperial: "Imperial (lbs, ft, gal)",
      numberFormat: "Number Format",
      regionalPreferences: "Regional Preferences",
      regionSettingsDescription: "These settings help customize your experience based on your location and preferences.",
      weekStartsOn: "Week starts on:",
      newsAndUpdates: "News and Updates",
      newsAboutProducts: "News about product and feature updates.",
      reminders: "Reminders",
      getRemindersDescription: "Get a notification to remind you of updates you might have missed.",
      pushNotifications: "Push Notifications",
      pushNotificationsDescription: "Get in-app notification about your savings and investments.",
      changePhotoProfile: "Change Photo Profile",
      delete: "Delete",
      save: "Save",
      saveChanges: "Save Changes",
      role: "Role",
      enterYourRole: "Enter your role",
      companyName: "Company Name",
      enterCompanyName: "Enter company name",
      companyEmail: "Company Email",
      enterCompanyEmail: "Enter company email",
      linkedin: "LinkedIn",
      enterLinkedinUrl: "Enter LinkedIn URL",
      dateOfIncorporation: "Date of Incorporation",
      countryOfHeadquartered: "Country of Headquartered",
      selectACountry: "Select a country",
      feedbackComingSoon: "Feedback form coming soon.",
      themeSettings: "Theme Settings",
      selectAppearance: "Choose your preferred appearance",
      lightModeDescription: "Light theme for daytime use",
      darkModeDescription: "Dark theme to reduce eye strain"
    }
  },
  es: {
    nav: { features: "Caracteristicas", faqs: "Preguntas frecuentes", newsletter: "Boletin", community: "Comunidad", blog: "Blog", scheduleDemo: "Programar Demo", signUp: "Registrarse", login: "Iniciar sesion" },
    hero: { title: "Transforma tus Finanzas con el Poder de la IA!", description: "Revoluciona tus finanzas con nuestra aplicacion impulsada por IA.", subscribe: "Suscribirse", emailPlaceholder: "Ingresa tu correo", notice: "Suscribete al boletin de Finquanta AI para las ultimas noticias." },
    features: { banner: "Optimizando decisiones financieras con tecnologia de IA.", title: "Nuestro asistente de IA se enfoca en lo que mas importa", tagline: "entregando estrategias financieras inteligentes para tu negocio.", maturity: "Madurez", maturityDesc: "Estrategias inteligentes para cada etapa, desde startup hasta crecimiento.", nature: "Naturaleza", natureDesc: "Perspectivas especificas de la industria para tomar mejores decisiones.", niche: "Nicho", nicheDesc: "Orientacion financiera basada en tu modelo de negocio.", financialHealth: "Salud Financiera", financialHealthDesc: "Mantente al tanto del flujo de caja, gastos y ganancias." },
    faq: { title: "Preguntas Frecuentes", q1: "Cuanto cuesta Finquanta AI?", a1: "Ofrecemos un plan gratuito con herramientas esenciales, mas planes de pago desde $49.99/mes.", q2: "Como funciona Finquanta AI?", a2: "Nuestra IA analiza las finanzas de tu negocio y proporciona recomendaciones inteligentes.", q3: "Cuales son los beneficios de usar Finquanta AI?", a3: "Ahorra tiempo, toma decisiones financieras mas inteligentes." },
    newsletter: { title: "Mantente informado", description: "Suscribete al boletin de Finquanta AI para las ultimas noticias.", emailPlaceholder: "Ingresa tu correo", subscribe: "Suscribirse" },
    community: { title: "Tambien puedes conectarte con nosotros en" },
    footer: { terms: "terminos de servicio", privacy: "aviso de privacidad", aiRisk: "divulgacion de riesgo de IA" },
    legal: { returnHome: "Volver a la pagina principal", termsTitle: "TERMINOS DE SERVICIO DE FINQUANTA", termsIntro: "Estos Terminos de Servicio rigen su acceso y uso de la plataforma Finquanta. Al crear una cuenta o usar la plataforma, acepta estos terminos.", privacyTitle: "AVISO DE PRIVACIDAD DE FINQUANTA", privacyIntro: "Finquanta se compromete a proteger la privacidad y seguridad de la informacion financiera y empresarial confiada por nuestros usuarios.", aiRiskTitle: "DIVULGACION DE RIESGO DE IA DE FINQUANTA", aiRiskIntro: "Finquanta utiliza inteligencia artificial, modelos de aprendizaje automatico y sistemas automatizados para ayudar a las empresas a gestionar datos financieros." },
    auth: { login: "Iniciar sesion", signUp: "Registrarse", email: "Correo electronico", password: "Contrasena", confirmPassword: "Confirmar contrasena", forgotPassword: "Olvido su contrasena?", rememberMe: "Recuerdame", loginButton: "Iniciar sesion", signUpButton: "Crear cuenta", alreadyHaveAccount: "Ya tiene una cuenta?", dontHaveAccount: "No tiene una cuenta?", loginWithGoogle: "Iniciar sesion con Google", signUpWithGoogle: "Registrarse con Google", resetPassword: "Restablecer tu contrasena", resetPasswordDesc: "Ingresa tu correo y te enviaremos un enlace de restablecimiento.", sendResetLink: "Enviar enlace de restablecimiento", backToSignIn: "Volver a iniciar sesion", checkEmail: "Revisa tu correo", resetLinkSent: "Enviamos un enlace de restablecimiento a" },
    dashboard: { title: "Panel de control", profileSettings: "Configuracion de perfil", termsOfService: "Terminos de servicio", privacyPolicy: "Politica de privacidad", search: "Buscar", balance: "Saldo", cashflow: "Flujo de efectivo", expense: "Gasto", bookkeeping: "Contabilidad", last30Days: "Ultimos 30 dias", addData: "Agregar datos", date: "Fecha", type: "Tipo", detail: "Detalle", price: "Precio", amount: "Cantidad", noTransactions: "Sin transacciones aun", totalRevenue: "Ingresos totales", noDataYet: "Sin datos aun", goals: "Objetivos", addGoal: "Agregar objetivo", noGoalsAdded: "Sin objetivos anadidos aun", bankAccount: "Cuenta bancaria", light: "Claro", dark: "Oscuro", version: "Version" },
    settings: {
      languageSettings: "Configuracion de idioma",
      displayLanguage: "Idioma de pantalla",
      changeLanguageAcrossSite: "Esto cambiara el idioma en todo el sitio.",
      notificationSettings: "Configuracion de notificaciones",
      selectNotificationPreference: "Selecciona tu preferencia de notificaciones",
      giveFeedback: "Dar retroalimentacion",
      logOut: "Cerrar sesion",
      deleteAccount: "Eliminar cuenta",
      deleteAccountWarning: "Cerrar tu cuenta no se puede deshacer. Asegurate de que el saldo de tu cuenta sea $0.00 antes de comenzar.",
      deleteAccountNow: "Eliminar cuenta ahora",
      languageRegion: "Idioma y region",
      configureLanguageSettings: "Configura tu idioma preferido, zona horaria y configuracion regional",
      timeZone: "Zona horaria",
      selectTimezone: "Selecciona zona horaria",
      currentTime: "Hora actual:",
      dateFormat: "Formato de fecha",
      today: "Hoy:",
      timeFormat: "Formato de hora",
      twelveHour: "12 horas (AM/PM)",
      twentyFourHour: "24 horas",
      currency: "Moneda",
      example: "Ejemplo:",
      measurementSystem: "Sistema de medicion",
      metric: "Metrico (kg, cm, L)",
      imperial: "Imperial (lbs, ft, gal)",
      numberFormat: "Formato numerico",
      regionalPreferences: "Preferencias regionales",
      regionSettingsDescription: "Esta configuracion ayuda a personalizar tu experiencia segun tu ubicacion y preferencias.",
      weekStartsOn: "La semana comienza el:",
      newsAndUpdates: "Noticias y actualizaciones",
      newsAboutProducts: "Noticias sobre actualizaciones de productos y caracteristicas.",
      reminders: "Recordatorios",
      getRemindersDescription: "Recibe una notificacion para recordarte actualizaciones que podrias haber perdido.",
      pushNotifications: "Notificaciones push",
      pushNotificationsDescription: "Recibe notificaciones en la aplicacion sobre tus ahorros e inversiones.",
      changePhotoProfile: "Cambiar foto de perfil",
      delete: "Eliminar",
      save: "Guardar",
      saveChanges: "Guardar cambios",
      role: "Rol",
      enterYourRole: "Ingresa tu rol",
      companyName: "Nombre de empresa",
      enterCompanyName: "Ingresa el nombre de la empresa",
      companyEmail: "Correo de empresa",
      enterCompanyEmail: "Ingresa el correo de la empresa",
      linkedin: "LinkedIn",
      enterLinkedinUrl: "Ingresa la URL de LinkedIn",
      dateOfIncorporation: "Fecha de constitucion",
      countryOfHeadquartered: "Pais de headquarters",
      selectACountry: "Selecciona un pais",
      feedbackComingSoon: "Formulario de retroalimentacion proxximamente.",
      themeSettings: "Configuracion de tema",
      selectAppearance: "Elige tu apariencia preferida",
      lightModeDescription: "Tema claro para uso diurno",
      darkModeDescription: "Tema oscuro para reducir la fatiga visual"
    }
  },
  fr: {
    nav: { features: "Fonctionnalites", faqs: "FAQ", newsletter: "Newsletter", community: "Communaute", blog: "Blog", scheduleDemo: "Planifier une demo", signUp: "S inscrire", login: "Connexion" },
    hero: { title: "Transformez vos finances avec la puissance de l IA!", description: "Revolutionnez vos finances avec notre application alimentee par l IA.", subscribe: "S abonner", emailPlaceholder: "Entrez votre email", notice: "Inscrivez-vous a la newsletter Finquanta AI pour les dernieres nouvelles." },
    features: { banner: "Optimiser les decisions financieres grace a la puissante technologie IA.", title: "Notre assistant IA se concentre sur ce qui compte le plus", tagline: "fournir des strategies financieres intelligentes pour votre entreprise.", maturity: "Maturite", maturityDesc: "Des strategies intelligentes pour chaque etape, du demarrage a la croissance.", nature: "Nature", natureDesc: "Des informations specifiques a l industrie pour prendre de meilleures decisions.", niche: "Niche", nicheDesc: "Conseils financiers bases sur votre modele d entreprise.", financialHealth: "Sante Financiere", financialHealthDesc: "Gardez le controle de vos flux de tresorerie, depenses et benefices." },
    faq: { title: "Questions Frequemment Posees", q1: "Combien coute Finquanta AI?", a1: "Nous offrons un plan gratuit avec des outils essentiels, plus des plans payants a partir de 49,99$/mois.", q2: "Comment fonctionne Finquanta AI?", a2: "Notre IA analyse vos finances d entreprise et fournit des recommandations intelligentes.", q3: "Quels sont les avantages de Finquanta AI?", a3: "Gagnez du temps, prenez de meilleures decisions financieres." },
    newsletter: { title: "Restez informe", description: "Inscrivez-vous a la newsletter Finquanta AI pour les dernieres nouvelles.", emailPlaceholder: "Entrez votre email", subscribe: "S abonner" },
    community: { title: "Vous pouvez egalement nous rejoindre sur" },
    footer: { terms: "conditions d utilisation", privacy: "avis de confidentialite", aiRisk: "divulgation des risques IA" },
    legal: { returnHome: "Retour a la page d accueil", termsTitle: "CONDITIONS D UTILISATION DE FINQUANTA", termsIntro: "Ces conditions d utilisation regissent votre acces et votre utilisation de la plateforme Finquanta. En creant un compte ou en utilisant la plateforme, vous acceptez ces conditions.", privacyTitle: "AVIS DE CONFIDENTIALITE DE FINQUANTA", privacyIntro: "Finquanta s engage a proteger la confidentialite et la securite des informations financieres et commerciales confiees par nos utilisateurs.", aiRiskTitle: "DIVULGATION DES RISQUES IA DE FINQUANTA", aiRiskIntro: "Finquanta utilise l intelligence artificielle, des modeles d apprentissage automatique et des systemes automatises pour aider les entreprises a gerer les donnees financieres." },
    auth: { login: "Connexion", signUp: "S inscrire", email: "Email", password: "Mot de passe", confirmPassword: "Confirmer le mot de passe", forgotPassword: "Mot de passe oublie?", rememberMe: "Se souvenir de moi", loginButton: "Connexion", signUpButton: "Creer un compte", alreadyHaveAccount: "Vous avez deja un compte?", dontHaveAccount: "Vous n avez pas de compte?", loginWithGoogle: "Connexion avec Google", signUpWithGoogle: "S inscrire avec Google", resetPassword: "Reinitialiser votre mot de passe", resetPasswordDesc: "Entrez votre email et nous vous enverrons un lien de reinitialisation.", sendResetLink: "Envoyer le lien de reinitialisation", backToSignIn: "Retour a la connexion", checkEmail: "Verifiez votre email", resetLinkSent: "Nous avons envoye un lien de reinitialisation a" },
    dashboard: { title: "Tableau de bord", profileSettings: "Parametres de profil", termsOfService: "Conditions de service", privacyPolicy: "Politique de confidentialite", search: "Rechercher", balance: "Solde", cashflow: "Tresorerie", expense: "Depense", bookkeeping: "Comptabilite", last30Days: "30 derniers jours", addData: "Ajouter des donnees", date: "Date", type: "Type", detail: "Detail", price: "Prix", amount: "Montant", noTransactions: "Aucune transaction pour l instant", totalRevenue: "Revenu total", noDataYet: "Pas de donnees pour l instant", goals: "Objectifs", addGoal: "Ajouter un objectif", noGoalsAdded: "Aucun objectif ajoute pour l instant", bankAccount: "Compte bancaire", light: "Clair", dark: "Sombre", version: "Version" },
    settings: {
      languageSettings: "Parametres de langue",
      displayLanguage: "Langue d affichage",
      changeLanguageAcrossSite: "Cela modifiera la langue sur l ensemble du site.",
      notificationSettings: "Parametres de notification",
      selectNotificationPreference: "Selectionnez votre preference de notification",
      giveFeedback: "Donner un avis",
      logOut: "Se deconnecter",
      deleteAccount: "Supprimer le compte",
      deleteAccountWarning: "La fermeture de votre compte ne peut pas etre annulee. Veuillez vous assurer que le solde de votre compte est de 0,00$ avant de commencer.",
      deleteAccountNow: "Supprimer le compte maintenant",
      languageRegion: "Langue et region",
      configureLanguageSettings: "Configurez votre langue preferee, votre fuseau horaire et vos parametres regionaux",
      timeZone: "Fuseau horaire",
      selectTimezone: "Selectionnez un fuseau horaire",
      currentTime: "Heure actuelle:",
      dateFormat: "Format de date",
      today: "Aujourd hui:",
      timeFormat: "Format d heure",
      twelveHour: "12 heures (AM/PM)",
      twentyFourHour: "24 heures",
      currency: "Devise",
      example: "Exemple:",
      measurementSystem: "Systeme de mesure",
      metric: "Metrique (kg, cm, L)",
      imperial: "Imperial (lbs, ft, gal)",
      numberFormat: "Format numerique",
      regionalPreferences: "Preferences regionales",
      regionSettingsDescription: "Ces parametres aident a personnaliser votre experience en fonction de votre localisation et de vos preferences.",
      weekStartsOn: "La semaine commence le:",
      newsAndUpdates: "Actualites et mises a jour",
      newsAboutProducts: "Actualites sur les mises a jour de produits et de fonctionnalites.",
      reminders: "Rappels",
      getRemindersDescription: "Recevez une notification pour vous rappeler les mises a jour que vous avez pu manquer.",
      pushNotifications: "Notifications push",
      pushNotificationsDescription: "Recevez une notification dans l application concernant vos economies et vos investissements.",
      changePhotoProfile: "Changer la photo de profil",
      delete: "Supprimer",
      save: "Enregistrer",
      saveChanges: "Enregistrer les modifications",
      role: "Role",
      enterYourRole: "Entrez votre role",
      companyName: "Nom de l entreprise",
      enterCompanyName: "Entrez le nom de l entreprise",
      companyEmail: "Email de l entreprise",
      enterCompanyEmail: "Entrez l email de l entreprise",
      linkedin: "LinkedIn",
      enterLinkedinUrl: "Entrez l URL LinkedIn",
      dateOfIncorporation: "Date de constitution",
      countryOfHeadquartered: "Pays du siege social",
      selectACountry: "Selectionnez un pays",
      feedbackComingSoon: "Formulaire de retour d information bientot disponible.",
      themeSettings: "Parametres de theme",
      selectAppearance: "Choisissez votre apparence preferee",
      lightModeDescription: "Theme clair pour une utilisation en journee",
      darkModeDescription: "Theme sombre pour reduire la fatigue oculaire"
    }
  },
  pt: {
    nav: { features: "Recursos", faqs: "Perguntas frequentes", newsletter: "Newsletter", community: "Comunidade", blog: "Blog", scheduleDemo: "Agendar Demo", signUp: "Cadastrar", login: "Entrar" },
    hero: { title: "Transforme suas Financas com o Poder da IA!", description: "Revolucione suas financas com nosso aplicativo de IA.", subscribe: "Inscrever-se", emailPlaceholder: "Digite seu email", notice: "Inscreva-se na newsletter da Finquanta AI para as ultimas noticias." },
    features: { banner: "Otimizando decisoes financeiras com tecnologia de IA poderosa.", title: "Nosso assistente de IA foca no que mais importa", tagline: "entregando estrategias financeiras inteligentes para o seu negocio.", maturity: "Maturidade", maturityDesc: "Estrategias inteligentes para cada etapa, do startup ao crescimento.", nature: "Natureza", natureDesc: "Insights especificos do setor para tomar melhores decisoes.", niche: "Nicho", nicheDesc: "Orientacao financeira baseada no seu modelo de negocio.", financialHealth: "Saude Financeira", financialHealthDesc: "Fique por dentro do fluxo de caixa, despesas e lucros." },
    faq: { title: "Perguntas Frequentes", q1: "Quanto custa o Finquanta AI?", a1: "Oferecemos um plano gratuito com ferramentas essenciais, mais planos pagos a partir de $49,99/mes.", q2: "Como funciona o Finquanta AI?", a2: "Nossa IA analisa as financas do seu negocio e fornece recomendacoes inteligentes.", q3: "Quais sao os beneficios do Finquanta AI?", a3: "Economize tempo, tome decisoes financeiras mais inteligentes." },
    newsletter: { title: "Fique por dentro", description: "Inscreva-se na newsletter da Finquanta AI para as ultimas noticias.", emailPlaceholder: "Digite seu email", subscribe: "Inscrever-se" },
    community: { title: "Voce tambem pode se conectar conosco em" },
    footer: { terms: "termos de servico", privacy: "aviso de privacidade", aiRisk: "divulgacao de risco de IA" },
    legal: { returnHome: "Voltar para a pagina inicial", termsTitle: "TERMOS DE SERVICO DA FINQUANTA", termsIntro: "Estes Termos de Servico regem o seu acesso e uso da plataforma Finquanta. Ao criar uma conta ou usar a plataforma, voce concorda com estes termos.", privacyTitle: "AVISO DE PRIVACIDADE DA FINQUANTA", privacyIntro: "A Finquanta esta comprometida em proteger a privacidade e seguranca das informacoes financeiras e empresariais confiadas pelos nossos usuarios.", aiRiskTitle: "DIVULGACAO DE RISCO DE IA DA FINQUANTA", aiRiskIntro: "A Finquanta utiliza inteligencia artificial, modelos de aprendizado de maquina e sistemas automatizados para ajudar empresas a gerenciar dados financieros." },
    auth: { login: "Entrar", signUp: "Cadastrar", email: "Email", password: "Senha", confirmPassword: "Confirmar senha", forgotPassword: "Esqueceu a senha?", rememberMe: "Lembrar-me", loginButton: "Entrar", signUpButton: "Criar conta", alreadyHaveAccount: "Ja tem uma conta?", dontHaveAccount: "Nao tem uma conta?", loginWithGoogle: "Entrar com Google", signUpWithGoogle: "Cadastrar com Google", resetPassword: "Redefinir sua senha", resetPasswordDesc: "Digite seu email e enviaremos um link de redefinicao.", sendResetLink: "Enviar link de redefinicao", backToSignIn: "Voltar para entrar", checkEmail: "Verifique seu email", resetLinkSent: "Enviamos um link de redefinicao de senha para" },
    dashboard: { title: "Painel de controle", profileSettings: "Configuracoes de perfil", termsOfService: "Termos de servico", privacyPolicy: "Politica de privacidade", search: "Pesquisar", balance: "Saldo", cashflow: "Fluxo de caixa", expense: "Despesa", bookkeeping: "Contabilidade", last30Days: "Ultimos 30 dias", addData: "Adicionar dados", date: "Data", type: "Tipo", detail: "Detalhe", price: "Preco", amount: "Quantidade", noTransactions: "Sem transacoes ainda", totalRevenue: "Receita total", noDataYet: "Sem dados ainda", goals: "Metas", addGoal: "Adicionar meta", noGoalsAdded: "Nenhuma meta adicionada ainda", bankAccount: "Conta bancaria", light: "Claro", dark: "Escuro", version: "Versao" },
    settings: {
      languageSettings: "Configuracoes de idioma",
      displayLanguage: "Idioma de exibicao",
      changeLanguageAcrossSite: "Isso mudara o idioma em todo o site.",
      notificationSettings: "Configuracoes de notificacao",
      selectNotificationPreference: "Selecione sua preferencia de notificacao",
      giveFeedback: "Enviar feedback",
      logOut: "Sair",
      deleteAccount: "Excluir conta",
      deleteAccountWarning: "Fechar sua conta nao pode ser desfeito. Verifique se o saldo de sua conta e $0,00 antes de comecear.",
      deleteAccountNow: "Excluir conta agora",
      languageRegion: "Idioma e regiao",
      configureLanguageSettings: "Configure seu idioma preferido, fuso horario e configuracoes regionais",
      timeZone: "Fuso horario",
      selectTimezone: "Selecione o fuso horario",
      currentTime: "Hora atual:",
      dateFormat: "Formato de data",
      today: "Hoje:",
      timeFormat: "Formato de hora",
      twelveHour: "12 horas (AM/PM)",
      twentyFourHour: "24 horas",
      currency: "Moeda",
      example: "Exemplo:",
      measurementSystem: "Sistema de medida",
      metric: "Metrico (kg, cm, L)",
      imperial: "Imperial (lbs, ft, gal)",
      numberFormat: "Formato numerico",
      regionalPreferences: "Preferencias regionais",
      regionSettingsDescription: "Essas configuracoes ajudam a personalizar sua experiencia com base em sua localizacao e preferencias.",
      weekStartsOn: "Semana comeca em:",
      newsAndUpdates: "Noticias e atualizacoes",
      newsAboutProducts: "Noticias sobre atualizacoes de produtos e recursos.",
      reminders: "Lembretes",
      getRemindersDescription: "Receba uma notificacao para lembrá-lo de atualizacoes que talvez tenha perdido.",
      pushNotifications: "Notificacoes push",
      pushNotificationsDescription: "Receba notificacao no aplicativo sobre sua economia e investimentos.",
      changePhotoProfile: "Alterar foto do perfil",
      delete: "Excluir",
      save: "Salvar",
      saveChanges: "Salvar alteracoes",
      role: "Funcao",
      enterYourRole: "Digite sua funcao",
      companyName: "Nome da empresa",
      enterCompanyName: "Digite o nome da empresa",
      companyEmail: "Email da empresa",
      enterCompanyEmail: "Digite o email da empresa",
      linkedin: "LinkedIn",
      enterLinkedinUrl: "Digite a URL do LinkedIn",
      dateOfIncorporation: "Data de constituicao",
      countryOfHeadquartered: "Pais da sede",
      selectACountry: "Selecione um pais",
      feedbackComingSoon: "Formulario de feedback em breve.",
      themeSettings: "Configuracoes de tema",
      selectAppearance: "Escolha sua aparencia preferida",
      lightModeDescription: "Tema claro para uso diurno",
      darkModeDescription: "Tema escuro para reduzir a fadiga visual"
    }
  },
  ar: {
    nav: { features: "الميزات", faqs: "الأسئلة الشائعة", newsletter: "النشرة الإخبارية", community: "المجتمع", blog: "المدونة", scheduleDemo: "جدولة عرض", signUp: "التسجيل", login: "تسجيل الدخول" },
    hero: { title: "حول أموالك بقوة الذكاء الاصطناعي!", description: "أحدث ثورة في أموالك مع تطبيقنا.", subscribe: "اشترك الآن", emailPlaceholder: "أدخل بريدك الإلكتروني", notice: "اشترك في نشرة Finquanta AI الإخبارية." },
    features: { banner: "تحسين الاقرارات المالية من خلال تقنية الذكاء الاصطناعي.", title: "يركز مساعدنا الذكي على ما يهم أكثر", tagline: "تقديم استراتيجيات مالية ذكية لعملك.", maturity: "النضج", maturityDesc: "استراتيجيات ذكية لكل مرحلة.", nature: "الطبيعة", natureDesc: "رؤى خاصة بالصناعة.", niche: "المجال", nicheDesc: "توجيه مالي بناء على نموذج عملك.", financialHealth: "الصحة المالية", financialHealthDesc: "ابق على اطلاع على التدفق النقدي والمصروفات." },
    faq: { title: "الأسئلة الشائعة", q1: "كم تكلفة Finquanta AIØŸ", a1: "نقدم خطة مجانية بأدوات أساسية، بالإضافة إلى خطط مدفوعة.", q2: "كيف يعمل Finquanta AIØŸ", a2: "يحلل الذكاء الاصطناعي أموالك ويقدم توصيات ذكية.", q3: "ما فوائد استخدام Finquanta AIØŸ", a3: "وفر الوقت واتخذ قرارات مالية أذكى." },
    newsletter: { title: "ابق على اطلاع", description: "اشترك في نشرة Finquanta AI الإخبارية.", emailPlaceholder: "أدخل بريدك الإلكتروني", subscribe: "اشترك الآن" },
    community: { title: "يمكنك أيضا الاتصال بنا على" },
    footer: { terms: "شروط الخدمة", privacy: "إشعار الخصوصية", aiRisk: "إفصاح مخاطر الذكاء الاصطناعي" },
    legal: { returnHome: "العودة إلى الصفحة الرئيسية", termsTitle: "شروط خدمة FINQUANTA", termsIntro: "تحكم شروط الخدمة هذه وصولك واستخدامك لمنصة Finquanta.", privacyTitle: "إشعار خصوصية FINQUANTA", privacyIntro: "تلتزم Finquanta بحماية خصوصية المعلومات المالية.", aiRiskTitle: "إفصاح مخاطر الذكاء الاصطناعي في FINQUANTA", aiRiskIntro: "تستخدم Finquanta الذكاء الاصطناعي والأنظمة الآلية لمساعدة الشركات." },
    auth: { login: "تسجيل الدخول", signUp: "التسجيل", email: "البريد الإلكتروني", password: "كلمة المرور", confirmPassword: "تأكيد كلمة المرور", forgotPassword: "هل نسيت كلمة المرور؟", rememberMe: "تذكرني", loginButton: "تسجيل الدخول", signUpButton: "إنشاء حساب", alreadyHaveAccount: "هل لديك حساب بالفعل؟", dontHaveAccount: "ليس لديك حساب؟", loginWithGoogle: "تسجيل الدخول عبر Google", signUpWithGoogle: "التسجيل عبر Google", resetPassword: "إعادة تعيين كلمة المرور", resetPasswordDesc: "أدخل بريدك الإلكتروني وسنرسل لك رابط إعادة التعيين.", sendResetLink: "إرسال رابط إعادة التعيين", backToSignIn: "العودة إلى تسجيل الدخول", checkEmail: "تحقق من بريدك الإلكتروني", resetLinkSent: "أرسلنا رابط إعادة تعيين كلمة المرور إلى" },
    dashboard: { title: "لوحة التحكم", profileSettings: "إعدادات الملف الشخصي", termsOfService: "شروط الخدمة", privacyPolicy: "سياسة الخصوصية", search: "البحث", balance: "الرصيد", cashflow: "تدفق النقد", expense: "المصروف", bookkeeping: "المحاسبة", last30Days: "آخر 30 يوم", addData: "إضافة بيانات", date: "التاريخ", type: "النوع", detail: "التفاصيل", price: "السعر", amount: "المبلغ", noTransactions: "لا توجد معاملات بعد", totalRevenue: "إجمالي الإيرادات", noDataYet: "لا توجد بيانات بعد", goals: "الأهداف", addGoal: "إضافة هدف", noGoalsAdded: "لم تضف أي أهداف بعد", bankAccount: "الحساب البنكي", light: "فاتح", dark: "غامق", version: "الإصدار" },
    settings: {
      languageSettings: "إعدادات اللغة",
      displayLanguage: "لغة العرض",
      changeLanguageAcrossSite: "سيؤدي هذا إلى تغيير اللغة في جميع أنحاء الموقع.",
      notificationSettings: "إعدادات الإشعارات",
      selectNotificationPreference: "حدد تفضيل الإشعارات الخاص بك",
      giveFeedback: "إرسال ملاحظات",
      logOut: "تسجيل الخروج",
      deleteAccount: "حذف الحساب",
      deleteAccountWarning: "لا يمكن التراجع عن إغلاق حسابك. تأكد من أن رصيد حسابك 0.00 دولار قبل البدء.",
      deleteAccountNow: "حذف الحساب الآن",
      languageRegion: "اللغة والمنطقة",
      configureLanguageSettings: "قم بتكوين لغتك المفضلة والمنطقة الزمنية والإعدادات الإقليمية",
      timeZone: "المنطقة الزمنية",
      selectTimezone: "اختر المنطقة الزمنية",
      currentTime: "الوقت الحالي:",
      dateFormat: "صيغة التاريخ",
      today: "اليوم:",
      timeFormat: "صيغة الوقت",
      twelveHour: "12 ساعة (صباحا/مساء)",
      twentyFourHour: "24 ساعة",
      currency: "العملة",
      example: "مثال:",
      measurementSystem: "نظام القياس",
      metric: "مترية (كجم، سم، لتر)",
      imperial: "إمبراطورية (جنيه، قدم، جالون)",
      numberFormat: "صيغة الأرقام",
      regionalPreferences: "التفضيلات الإقليمية",
      regionSettingsDescription: "تساعد هذه الإعدادات في تخصيص تجربتك بناء على موقعك والتفضيلات.",
      weekStartsOn: "تبدأ الأسبوع يوم:",
      newsAndUpdates: "الأخبار والتحديثات",
      newsAboutProducts: "أخبار عن تحديثات المنتجات والميزات.",
      reminders: "تذكيرات",
      getRemindersDescription: "احصل على إشعار لتذكيرك بالتحديثات التي قد تكون فاتتك.",
      pushNotifications: "إشعارات فورية",
      pushNotificationsDescription: "احصل على إشعار في التطبيق حول مدخراتك واستثماراتك.",
      changePhotoProfile: "تغيير صورة الملف الشخصي",
      delete: "حذف",
      save: "حفظ",
      saveChanges: "حفظ التغييرات",
      role: "الدور",
      enterYourRole: "أدخل دورك",
      companyName: "اسم الشركة",
      enterCompanyName: "أدخل اسم الشركة",
      companyEmail: "بريد الشركة",
      enterCompanyEmail: "أدخل بريد الشركة",
      linkedin: "LinkedIn",
      enterLinkedinUrl: "أدخل عنوان URL لـ LinkedIn",
      dateOfIncorporation: "تاريخ التأسيس",
      countryOfHeadquartered: "دولة المقر الرئيسي",
      selectACountry: "اختر دولة",
      feedbackComingSoon: "نموذج الملاحظات قريبا.",
      themeSettings: "إعدادات المظهر",
      selectAppearance: "اختر مظهرك المفضل",
      lightModeDescription: "مظهر فاتح لاستخدام النهار",
      darkModeDescription: "مظهر غامق لتقليل إجهاد العين"
    }
  },
  zh: {
    nav: { features: "功能", faqs: "常见问题", newsletter: "新闻通讯", community: "社区", blog: "博客", scheduleDemo: "安排演示", signUp: "注册", login: "登录" },
    hero: { title: "用AI的力量改变您的财务!", description: "用我们的AI应用程序彻底改变您的财务管理。", subscribe: "立即订阅", emailPlaceholder: "输入您的邮箱", notice: "订阅Finquanta AI新闻通讯获取最新信息。" },
    features: { banner: "通过强大的AI技术优化财务决策。", title: "我们的AI助手专注于最重要的事情", tagline: "为您的业务提供智能财务战略。", maturity: "成熟度", maturityDesc: "智能策略针对每个阶段。", nature: "性质", natureDesc: "特定行业的见解。", niche: "利基", nicheDesc: "基于您的业务模式的财务指导。", financialHealth: "财务健康", financialHealthDesc: "掌握您的现金流、支出和利润。" },
    faq: { title: "常见问题", q1: "Finquanta AI的费用是多少?", a1: "我们提供免费计划和付费计划。", q2: "Finquanta AI如何工作?", a2: "我们的AI分析您的业务财务并提供智能建议。", q3: "使用Finquanta AI的好处是什么?", a3: "节省时间，做出更聪明的财务决定。" },
    newsletter: { title: "了解最新信息", description: "订阅Finquanta AI新闻通讯获取最新信息。", emailPlaceholder: "输入您的邮箱", subscribe: "立即订阅" },
    community: { title: "您也可以在以下地方与我们联系" },
    footer: { terms: "服务条款", privacy: "隐私通知", aiRisk: "AI风险披露" },
    legal: { returnHome: "返回首页", termsTitle: "FINQUANTA服务条款", termsIntro: "这些服务条款管理您对Finquanta平台的访问和使用。", privacyTitle: "FINQUANTA隐私通知", privacyIntro: "Finquanta致力于保护财务信息的隐私和安全。", aiRiskTitle: "FINQUANTA AI风险披露", aiRiskIntro: "Finquanta使用人工智能和自动化系统来帮助企业管理财务数据。" },
    auth: { login: "登录", signUp: "注册", email: "电邮件", password: "密码", confirmPassword: "确认密码", forgotPassword: "忘记密码?", rememberMe: "记住我", loginButton: "登录", signUpButton: "创建帐户", alreadyHaveAccount: "已有帐户?", dontHaveAccount: "没有帐户?", loginWithGoogle: "使用Google登录", signUpWithGoogle: "使用Google注册", resetPassword: "重置您的密码", resetPasswordDesc: "输入您的电邮件，我们将发送重置链接。", sendResetLink: "发送重置链接", backToSignIn: "返回登录", checkEmail: "检查您的电邮件", resetLinkSent: "我们已将密码重置链接发送至" },
    dashboard: { title: "仪表板", profileSettings: "配置文件设置", termsOfService: "服务条款", privacyPolicy: "隐私政策", search: "搜索", balance: "余额", cashflow: "现金流", expense: "支出", bookkeeping: "簿记", last30Days: "最后30天", addData: "添加数据", date: "日期", type: "类型", detail: "详情", price: "价格", amount: "金额", noTransactions: "还没有交易", totalRevenue: "总收入", noDataYet: "还没有数据", goals: "目标", addGoal: "添加目标", noGoalsAdded: "还没有添加任何目标", bankAccount: "银行帐户", light: "浅色", dark: "深色", version: "版本" },
    settings: {
      languageSettings: "语言设置",
      displayLanguage: "显示语言",
      changeLanguageAcrossSite: "这将改变整个网站的语言。",
      notificationSettings: "通知设置",
      selectNotificationPreference: "选择您的通知偏好",
      giveFeedback: "提供反馈",
      logOut: "登出",
      deleteAccount: "删除帐户",
      deleteAccountWarning: "关闭您的帐户无法撤销。确保您的帐户余额为$0.00后再开始。",
      deleteAccountNow: "立即删除帐户",
      languageRegion: "语言和地区",
      configureLanguageSettings: "配置您首选的语言、时区和地区设置",
      timeZone: "时区",
      selectTimezone: "选择时区",
      currentTime: "当前时间:",
      dateFormat: "日期格式",
      today: "今天:",
      timeFormat: "时间格式",
      twelveHour: "12小时（上午/下午）",
      twentyFourHour: "24小时",
      currency: "货币",
      example: "例:",
      measurementSystem: "度量系统",
      metric: "公制（千克、厘米、升）",
      imperial: "帝国制（磅、英尺、加仑）",
      numberFormat: "数字格式",
      regionalPreferences: "地区偏好",
      regionSettingsDescription: "这些设置帮助根据您的位置和偏好自定义您的体验。",
      weekStartsOn: "周开始于:",
      newsAndUpdates: "新闻和更新",
      newsAboutProducts: "关于产品和功能更新的新闻。",
      reminders: "提醒",
      getRemindersDescription: "收到通知以提醒您可能错过的更新。",
      pushNotifications: "推送通知",
      pushNotificationsDescription: "收到关于您的节省和投资的应用内通知。",
      changePhotoProfile: "更改个人资料照片",
      delete: "删除",
      save: "保存",
      saveChanges: "保存更改",
      role: "角色",
      enterYourRole: "输入您的角色",
      companyName: "公司名称",
      enterCompanyName: "输入公司名称",
      companyEmail: "公司邮箱",
      enterCompanyEmail: "输入公司邮箱",
      linkedin: "LinkedIn",
      enterLinkedinUrl: "输入LinkedIn网址",
      dateOfIncorporation: "成立日期",
      countryOfHeadquartered: "总部所在国",
      selectACountry: "选择国家",
      feedbackComingSoon: "反馈表即将推出。",
      themeSettings: "主题设置",
      selectAppearance: "选择您喜欢的外观",
      lightModeDescription: "用于白天使用的浅色主题",
      darkModeDescription: "深色主题可减少眼睛疲劳"
    }
  },
  ja: {
    nav: { features: "機能", faqs: "よくある質問", newsletter: "ニュースレター", community: "コミュニティ", blog: "ブログ", scheduleDemo: "デモをスケジュール", signUp: "サインアップ", login: "ログイン" },
    hero: { title: "AIの力であなたの財務を変える!", description: "AIアプリで財務を革命化しましょう。", subscribe: "今すぐ購読", emailPlaceholder: "メールアドレスを入力", notice: "Finquanta AIニュースレターに登録して最新情報を取得。" },
    features: { banner: "強力なAI技術で財務決定を最適化。", title: "当社のAIアシスタントは最も重要なことに焦点を当てています", tagline: "ビジネスのための賢い財務戦略を提供します。", maturity: "成熟度", maturityDesc: "各段階のための賢い戦略。", nature: "性質", natureDesc: "業界固有の洞察。", niche: "ニッチ", nicheDesc: "ビジネスモデルに基づいた財務指導。", financialHealth: "財務健全性", financialHealthDesc: "キャッシュフロー、支出、利益を把握。" },
    faq: { title: "よくある質問", q1: "Finquanta AIの費用は?", a1: "無料プランと有料プランを提供しています。", q2: "Finquanta AIはどのように機能しますか?", a2: "私たちのAIがあなたの財務を分析し、スマートな提案を提供します。", q3: "Finquanta AIの利点は何ですか?", a3: "時間を節約し、より賢い財務決定を下します。" },
    newsletter: { title: "最新情報を取得", description: "Finquanta AIニュースレターに登録して最新情報を取得。", emailPlaceholder: "メールアドレスを入力", subscribe: "今すぐ購読" },
    community: { title: "以下でも私たちに接続できます" },
    footer: { terms: "利用規約", privacy: "プライバシー通知", aiRisk: "AIリスク開示" },
    legal: { returnHome: "ホームページに戻る", termsTitle: "FINQUANTAサービス利用規約", termsIntro: "これらの利用規約はFinquantaプラットフォームへのアクセスと使用を管理します。", privacyTitle: "FINQUANTAプライバシー通知", privacyIntro: "Finquantaは財務情報のプライバシーとセキュリティを保護することに専念しています。", aiRiskTitle: "FINQUANTA AIリスク開示", aiRiskIntro: "Finquantaは企業が財務データを管理するために人工知能と自動化システムを使用しています。" },
    auth: { login: "ログイン", signUp: "サインアップ", email: "メール", password: "パスワード", confirmPassword: "パスワードを確認", forgotPassword: "パスワードをお忘れですか?", rememberMe: "私を覚えておいて", loginButton: "ログイン", signUpButton: "アカウントを作成", alreadyHaveAccount: "既にアカウントをお持ちですか?", dontHaveAccount: "アカウントをお持ちではありませんか?", loginWithGoogle: "Googleでログイン", signUpWithGoogle: "Googleでサインアップ", resetPassword: "パスワードをリセット", resetPasswordDesc: "メールアドレスを入力してください。リセットリンクを送信します。", sendResetLink: "リセットリンクを送信", backToSignIn: "ログインに戻る", checkEmail: "メールを確認", resetLinkSent: "パスワードリセットリンクを次のアドレスに送信しました" },
    dashboard: { title: "ダッシュボード", profileSettings: "プロフィール設定", termsOfService: "サービス利用規約", privacyPolicy: "プライバシーポリシー", search: "検索", balance: "残高", cashflow: "キャッシュフロー", expense: "支出", bookkeeping: "簿記", last30Days: "過去30日", addData: "データを追加", date: "日付", type: "タイプ", detail: "詳細", price: "価格", amount: "金額", noTransactions: "まだトランザクションがありません", totalRevenue: "総収益", noDataYet: "まだデータがありません", goals: "目標", addGoal: "目標を追加", noGoalsAdded: "まだ目標が追加されていません", bankAccount: "銀行口座", light: "ライト", dark: "ダーク", version: "バージョン" },
    settings: {
      languageSettings: "言語設定",
      displayLanguage: "表示言語",
      changeLanguageAcrossSite: "これはサイト全体の言語を変更します。",
      notificationSettings: "通知設定",
      selectNotificationPreference: "通知の環境設定を選択",
      giveFeedback: "フィードバックを提供",
      logOut: "ログアウト",
      deleteAccount: "アカウントを削除",
      deleteAccountWarning: "アカウントを閉じることは取り消せません。開始する前に、アカウント残高が$0.00であることを確認してください。",
      deleteAccountNow: "今すぐアカウントを削除",
      languageRegion: "言語と地域",
      configureLanguageSettings: "希望の言語、タイムゾーン、地域設定を構成",
      timeZone: "タイムゾーン",
      selectTimezone: "タイムゾーンを選択",
      currentTime: "現在の時刻:",
      dateFormat: "日付形式",
      today: "今日:",
      timeFormat: "時間形式",
      twelveHour: "12時間（午前/午後）",
      twentyFourHour: "24時間",
      currency: "通貨",
      example: "例:",
      measurementSystem: "計測システム",
      metric: "メートル法（kg、cm、L）",
      imperial: "帝国制度（ポンド、フィート、ガロン）",
      numberFormat: "数値形式",
      regionalPreferences: "地域設定",
      regionSettingsDescription: "これらの設定は、位置と環境設定に基づいて体験をカスタマイズするのに役立ちます。",
      weekStartsOn: "週の始まり:",
      newsAndUpdates: "ニュースと更新",
      newsAboutProducts: "製品とフィーチャー更新に関するニュース。",
      reminders: "リマインダー",
      getRemindersDescription: "見逃したかもしれない更新を思い出させるための通知を受け取ります。",
      pushNotifications: "プッシュ通知",
      pushNotificationsDescription: "貯蓄と投資に関するアプリ内通知を受け取ります。",
      changePhotoProfile: "プロフィール写真を変更",
      delete: "削除",
      save: "保存",
      saveChanges: "変更を保存",
      role: "役割",
      enterYourRole: "あなたの役割を入力",
      companyName: "会社名",
      enterCompanyName: "会社名を入力",
      companyEmail: "会社メール",
      enterCompanyEmail: "会社メールを入力",
      linkedin: "LinkedIn",
      enterLinkedinUrl: "LinkedInのURLを入力",
      dateOfIncorporation: "設立日",
      countryOfHeadquartered: "本社所在地",
      selectACountry: "国を選択",
      feedbackComingSoon: "フィードバックフォームは近日公開予定です。",
      themeSettings: "テーマ設定",
      selectAppearance: "希望の外観を選択",
      lightModeDescription: "昼間使用のためのライトテーマ",
      darkModeDescription: "目の疲れを軽減するダークテーマ"
    }
  },
  ru: {
    nav: { features: "Функции", faqs: "ЧЗВ", newsletter: "Информационный бюллетень", community: "Сообщество", blog: "Блог", scheduleDemo: "Запланировать демонстрацию", signUp: "Зарегистрироваться", login: "Вход" },
    hero: { title: "Преобразуйте свои финансы с помощью искусственного интеллекта!", description: "Революционизируйте ваши финансы с помощью нашего приложения на основе ИИ.", subscribe: "Подписаться", emailPlaceholder: "Введите ваш email", notice: "Подпишитесь на рассылку Finquanta AI для получения последних новостей." },
    features: { banner: "Оптимизация финансовых решений с помощью мощной технологии ИИ.", title: "Наш умный помощник сосредоточен на самом важном", tagline: "предоставление умных финансовых стратегий для вашего бизнеса.", maturity: "Зрелость", maturityDesc: "Умные стратегии для каждого этапа.", nature: "Природа", natureDesc: "Отраслевые идеи.", niche: "Ниша", nicheDesc: "Финансовое руководство на основе вашей бизнес-модели.", financialHealth: "Финансовое здоровье", financialHealthDesc: "Будьте в курсе своего денежного потока, расходов и прибыли." },
    faq: { title: "Часто Задаваемые Вопросы", q1: "Сколько стоит Finquanta AI?", a1: "Мы предлагаем бесплатный план и платные планы.", q2: "Как работает Finquanta AI?", a2: "Наш ИИ анализирует ваши финансы и дает умные рекомендации.", q3: "Каковы преимущества Finquanta AI?", a3: "Экономьте время и принимайте более разумные финансовые решения." },
    newsletter: { title: "Оставайтесь в курсе", description: "Подпишитесь на рассылку Finquanta AI для получения последних новостей.", emailPlaceholder: "Введите ваш email", subscribe: "Подписаться" },
    community: { title: "Вы также можете связаться с нами на" },
    footer: { terms: "условия обслуживания", privacy: "уведомление о конфиденциальности", aiRisk: "раскрытие рисков ИИ" },
    legal: { returnHome: "Вернуться на главную", termsTitle: "Условия обслуживания FINQUANTA", termsIntro: "Эти условия обслуживания регулируют ваш доступ и использование платформы Finquanta.", privacyTitle: "Уведомление о конфиденциальности FINQUANTA", privacyIntro: "Finquanta стремится защищать конфиденциальность и безопасность финансовой информации.", aiRiskTitle: "Раскрытие рисков ИИ FINQUANTA", aiRiskIntro: "Finquanta использует искусственный интеллект и автоматизированные системы для управления финансовыми данными." },
    auth: { login: "Вход", signUp: "Зарегистрироваться", email: "Email", password: "Пароль", confirmPassword: "Подтвердить пароль", forgotPassword: "Забыли пароль?", rememberMe: "Запомнить меня", loginButton: "Вход", signUpButton: "Создать аккаунт", alreadyHaveAccount: "Уже есть аккаунт?", dontHaveAccount: "Нет аккаунта?", loginWithGoogle: "Вход через Google", signUpWithGoogle: "Регистрация через Google", resetPassword: "Сбросить пароль", resetPasswordDesc: "Введите ваш email и мы отправим вам ссылку для сброса.", sendResetLink: "Отправить ссылку для сброса", backToSignIn: "Вернуться к входу", checkEmail: "Проверьте ваш email", resetLinkSent: "Мы отправили ссылку для сброса пароля на" },
    dashboard: { title: "Панель управления", profileSettings: "Параметры профиля", termsOfService: "Условия обслуживания", privacyPolicy: "Политика конфиденциальности", search: "Поиск", balance: "Баланс", cashflow: "Денежный поток", expense: "Расход", bookkeeping: "Бухгалтерский учет", last30Days: "Последние 30 дней", addData: "Добавить данные", date: "Дата", type: "Тип", detail: "Деталь", price: "Цена", amount: "Сумма", noTransactions: "Пока нет транзакций", totalRevenue: "Общий доход", noDataYet: "Пока нет данных", goals: "Цели", addGoal: "Добавить цель", noGoalsAdded: "Цели еще не добавлены", bankAccount: "Банковский счет", light: "Свет", dark: "Темно", version: "Версия" },
    settings: {
      languageSettings: "Параметры языка",
      displayLanguage: "Язык отображения",
      changeLanguageAcrossSite: "Это изменит язык на всем сайте.",
      notificationSettings: "Параметры уведомлений",
      selectNotificationPreference: "Выберите предпочтение уведомлений",
      giveFeedback: "Оставить отзыв",
      logOut: "Выход",
      deleteAccount: "Удалить аккаунт",
      deleteAccountWarning: "Закрытие вашего аккаунта невозможно отменить. Убедитесь, что баланс вашего аккаунта составляет $0.00 перед началом.",
      deleteAccountNow: "Удалить аккаунт сейчас",
      languageRegion: "Язык и регион",
      configureLanguageSettings: "Настройте предпочитаемый язык, часовой пояс и региональные параметры",
      timeZone: "Часовой пояс",
      selectTimezone: "Выберите часовой пояс",
      currentTime: "Текущее время:",
      dateFormat: "Формат даты",
      today: "Сегодня:",
      timeFormat: "Формат времени",
      twelveHour: "12 часов (AM/PM)",
      twentyFourHour: "24 часа",
      currency: "Валюта",
      example: "Пример:",
      measurementSystem: "Система измерения",
      metric: "Метрическая (кг, см, л)",
      imperial: "Имперская (фунты, футы, галлоны)",
      numberFormat: "Числовой формат",
      regionalPreferences: "Региональные предпочтения",
      regionSettingsDescription: "Эти параметры помогают настроить ваш опыт в зависимости от вашего местоположения и предпочтений.",
      weekStartsOn: "Неделя начинается с:",
      newsAndUpdates: "Новости и обновления",
      newsAboutProducts: "Новости об обновлениях продуктов и функций.",
      reminders: "Напоминания",
      getRemindersDescription: "Получайте уведомления о пропущенных обновлениях.",
      pushNotifications: "Пушь-уведомления",
      pushNotificationsDescription: "Получайте уведомления в приложении о ваших сбережениях и инвестициях.",
      changePhotoProfile: "Изменить фото профиля",
      delete: "Удалить",
      save: "Сохранить",
      saveChanges: "Сохранить изменения",
      role: "Роль",
      enterYourRole: "Введите вашу роль",
      companyName: "Название компании",
      enterCompanyName: "Введите название компании",
      companyEmail: "Email компании",
      enterCompanyEmail: "Введите email компании",
      linkedin: "LinkedIn",
      enterLinkedinUrl: "Введите URL LinkedIn",
      dateOfIncorporation: "Дата регистрации",
      countryOfHeadquartered: "Страна штаб-квартиры",
      selectACountry: "Выберите страну",
      feedbackComingSoon: "Форма обратной связи скоро.",
      themeSettings: "Настройки темы",
      selectAppearance: "Выберите предпочитаемый внешний вид",
      lightModeDescription: "Светлая тема для использования в течение дня",
      darkModeDescription: "Темная тема для снижения нагрузки на глаза"
    }
  },
  nl: {
    nav: { features: "Functies", faqs: "Veelgestelde vragen", newsletter: "Nieuwsbrief", community: "Gemeenschap", blog: "Blog", scheduleDemo: "Demo plannen", signUp: "Registreren", login: "Inloggen" },
    hero: { title: "Transformeer je financien met AI-kracht!", description: "Revolutioneer je financien met onze AI-app.", subscribe: "Abonneer nu", emailPlaceholder: "Voer uw e-mail in", notice: "Abonneer u op de Finquanta AI-nieuwsbrief voor het laatste nieuws." },
    features: { banner: "Optimaliseer financiele beslissingen met krachtige AI-technologie.", title: "Onze AI-assistent richt zich op wat het meest belangrijk is", tagline: "slimme financiele strategieen voor uw bedrijf.", maturity: "Volwassenheid", maturityDesc: "Slimme strategieen voor elk stadium.", nature: "Aard", natureDesc: "Branchespecifieke inzichten.", niche: "Niche", nicheDesc: "Financiele begeleiding op basis van uw bedrijfsmodel.", financialHealth: "Financiele gezondheid", financialHealthDesc: "Blijf op de hoogte van uw cashflow, uitgaven en winst." },
    faq: { title: "Veelgestelde vragen", q1: "Hoeveel kost Finquanta AI?", a1: "We bieden een gratis plan en betaalde abonnementen.", q2: "Hoe werkt Finquanta AI?", a2: "Onze AI analyseert uw financien en geeft slimme aanbevelingen.", q3: "Wat zijn de voordelen van Finquanta AI?", a3: "Bespaar tijd en neem slimmere financiele beslissingen." },
    newsletter: { title: "Blijf op de hoogte", description: "Abonneer u op de Finquanta AI-nieuwsbrief voor het laatste nieuws.", emailPlaceholder: "Voer uw e-mail in", subscribe: "Abonneer nu" },
    community: { title: "U kunt ons ook bereiken op" },
    footer: { terms: "servicevoorwaarden", privacy: "privacykennisgeving", aiRisk: "AI-risico-openbaring" },
    legal: { returnHome: "Terug naar startpagina", termsTitle: "FINQUANTA SERVICEVOORWAARDEN", termsIntro: "Deze servicevoorwaarden beheren uw toegang tot en gebruik van het Finquanta-platform.", privacyTitle: "FINQUANTA PRIVACYKENNISGEVING", privacyIntro: "Finquanta zet zich in voor het beschermen van de privacy en veiligheid van financiele informatie.", aiRiskTitle: "FINQUANTA AI-RISICO-OPENBARING", aiRiskIntro: "Finquanta maakt gebruik van kunstmatige intelligentie en geautomatiseerde systemen voor financieel beheer." },
    auth: { login: "Inloggen", signUp: "Registreren", email: "E-mail", password: "Wachtwoord", confirmPassword: "Wachtwoord bevestigen", forgotPassword: "Wachtwoord vergeten?", rememberMe: "Onthoud mij", loginButton: "Inloggen", signUpButton: "Account aanmaken", alreadyHaveAccount: "Heeft u al een account?", dontHaveAccount: "Geen account?", loginWithGoogle: "Inloggen met Google", signUpWithGoogle: "Registreren met Google", resetPassword: "Wachtwoord opnieuw instellen", resetPasswordDesc: "Voer uw e-mail in en we sturen u een resetlink.", sendResetLink: "Resetlink verzenden", backToSignIn: "Terug naar inloggen", checkEmail: "Controleer uw e-mail", resetLinkSent: "We hebben een resetlink gestuurd naar" },
    dashboard: { title: "Dashboard", profileSettings: "Profielinstellingen", termsOfService: "Servicevoorwaarden", privacyPolicy: "Privacybeleid", search: "Zoeken", balance: "Saldo", cashflow: "Cashflow", expense: "Uitgaven", bookkeeping: "Boekhouding", last30Days: "Afgelopen 30 dagen", addData: "Gegevens toevoegen", date: "Datum", type: "Type", detail: "Detail", price: "Prijs", amount: "Bedrag", noTransactions: "Nog geen transacties", totalRevenue: "Totale opbrengst", noDataYet: "Nog geen gegevens", goals: "Doelen", addGoal: "Doel toevoegen", noGoalsAdded: "Nog geen doelen toegevoegd", bankAccount: "Bankrekening", light: "Licht", dark: "Donker", version: "Versie" },
    settings: {
      languageSettings: "Taalinstellingen",
      displayLanguage: "Weergavetaal",
      changeLanguageAcrossSite: "Dit zal de taal op de hele site veranderen.",
      notificationSettings: "Meldingsinstellingen",
      selectNotificationPreference: "Selecteer uw meldingsvoorkeur",
      giveFeedback: "Feedback geven",
      logOut: "Afmelden",
      deleteAccount: "Account verwijderen",
      deleteAccountWarning: "Het sluiten van uw account kan niet ongedaan worden gemaakt. Zorg ervoor dat uw accountsaldo $0,00 is voordat u begint.",
      deleteAccountNow: "Account nu verwijderen",
      languageRegion: "Taal en regio",
      configureLanguageSettings: "Configureer uw voorkeurstaal, tijdzone en regionale instellingen",
      timeZone: "Tijdzone",
      selectTimezone: "Selecteer tijdzone",
      currentTime: "Huidige tijd:",
      dateFormat: "Datumformat",
      today: "Vandaag:",
      timeFormat: "Tijdformat",
      twelveHour: "12 uur (AM/PM)",
      twentyFourHour: "24 uur",
      currency: "Valuta",
      example: "Voorbeeld:",
      measurementSystem: "Meetsysteem",
      metric: "Metriek (kg, cm, L)",
      imperial: "Imperiaal (lbs, ft, gal)",
      numberFormat: "Getalformat",
      regionalPreferences: "Regionale voorkeuren",
      regionSettingsDescription: "Deze instellingen helpen uw ervaring aan te passen op basis van uw locatie en voorkeuren.",
      weekStartsOn: "Week begint op:",
      newsAndUpdates: "Nieuws en updates",
      newsAboutProducts: "Nieuws over product- en functieupdates.",
      reminders: "Herinneringen",
      getRemindersDescription: "Ontvang een melding om u te herinneren aan updates die u mogelijk hebt gemist.",
      pushNotifications: "Pushberichten",
      pushNotificationsDescription: "Ontvang een melding in de app over uw besparingen en investeringen.",
      changePhotoProfile: "Profielfoto wijzigen",
      delete: "Verwijderen",
      save: "Opslaan",
      saveChanges: "Wijzigingen opslaan",
      role: "Rol",
      enterYourRole: "Voer uw rol in",
      companyName: "Bedrijfsnaam",
      enterCompanyName: "Voer bedrijfsnaam in",
      companyEmail: "Bedrijfse-mail",
      enterCompanyEmail: "Voer bedrijfse-mail in",
      linkedin: "LinkedIn",
      enterLinkedinUrl: "Voer LinkedIn-URL in",
      dateOfIncorporation: "Oprichtingsdatum",
      countryOfHeadquartered: "Land van zetelvestiging",
      selectACountry: "Selecteer een land",
      feedbackComingSoon: "Feedbackformulier binnenkort beschikbaar.",
      themeSettings: "Thema-instellingen",
      selectAppearance: "Selecteer uw voorkeuruiterlijk",
      lightModeDescription: "Licht thema voor dagtijds gebruik",
      darkModeDescription: "Donker thema om oogvermoeidheid te verminderen"
    }
  },
  de: {
    nav: { features: "Funktionen", faqs: "Haufig gestellte Fragen", newsletter: "Newsletter", community: "Gemeinschaft", blog: "Blog", scheduleDemo: "Demo planen", signUp: "Anmelden", login: "Anmelden" },
    hero: { title: "Transformieren Sie Ihre Finanzen mit KI-Kraft!", description: "Revolutionieren Sie Ihre Finanzen mit unserer KI-App.", subscribe: "Jetzt abonnieren", emailPlaceholder: "Geben Sie Ihre E-Mail ein", notice: "Abonnieren Sie den Finquanta AI-Newsletter fur die neuesten Nachrichten." },
    features: { banner: "Optimieren Sie finanzielle Entscheidungen mit leistungsstarker KI-Technologie.", title: "Unser KI-Assistent konzentriert sich auf das Wichtigste", tagline: "intelligente Finanzstrategien fur Ihr Unternehmen.", maturity: "Reife", maturityDesc: "Intelligente Strategien fur jede Phase.", nature: "Natur", natureDesc: "Branchenspezifische Erkenntnisse.", niche: "Nische", nicheDesc: "Finanzielle Anleitung basierend auf Ihrem Geschaftsmodell.", financialHealth: "Finanzielle Gesundheit", financialHealthDesc: "Behalten Sie Ihren Cashflow, Ihre Ausgaben und Ihren Gewinn im Auge." },
    faq: { title: "Haufig gestellte Fragen", q1: "Wie viel kostet Finquanta AI?", a1: "Wir bieten einen kostenlosen Plan und bezahlte Abonnements.", q2: "Wie funktioniert Finquanta AI?", a2: "Unsere KI analysiert Ihre Finanzen und gibt intelligente Empfehlungen.", q3: "Was sind die Vorteile von Finquanta AI?", a3: "Sparen Sie Zeit und treffen Sie intelligentere finanzielle Entscheidungen." },
    newsletter: { title: "Bleiben Sie auf dem Laufenden", description: "Abonnieren Sie den Finquanta AI-Newsletter fur die neuesten Nachrichten.", emailPlaceholder: "Geben Sie Ihre E-Mail ein", subscribe: "Jetzt abonnieren" },
    community: { title: "Sie konnen uns auch auf erreichen" },
    footer: { terms: "Servicebedingungen", privacy: "Datenschutzerklarung", aiRisk: "KI-Risiko-Offenlegung" },
    legal: { returnHome: "Zur Startseite", termsTitle: "FINQUANTA SERVICEBEDINGUNGEN", termsIntro: "Diese Servicebedingungen regeln Ihren Zugriff auf und Ihre Nutzung der Finquanta-Plattform.", privacyTitle: "FINQUANTA DATENSCHUTZERKLARUNG", privacyIntro: "Finquanta setzt sich dafur ein, die Privatsphare und Sicherheit von Finanzinformationen zu schutzen.", aiRiskTitle: "FINQUANTA KI-RISIKO-OFFENLEGUNG", aiRiskIntro: "Finquanta verwendet kunstliche Intelligenz und automatisierte Systeme zur Verwaltung von Finanzdaten." },
    auth: { login: "Anmelden", signUp: "Registrieren", email: "Email", password: "Passwort", confirmPassword: "Passwort bestatigen", forgotPassword: "Passwort vergessen?", rememberMe: "Merken Sie mich", loginButton: "Anmelden", signUpButton: "Konto erstellen", alreadyHaveAccount: "Sie haben bereits ein Konto?", dontHaveAccount: "Sie haben kein Konto?", loginWithGoogle: "Mit Google anmelden", signUpWithGoogle: "Mit Google registrieren", resetPassword: "Passwort zurucksetzen", resetPasswordDesc: "Geben Sie Ihre E-Mail ein und wir senden Ihnen einen Reset-Link.", sendResetLink: "Reset-Link senden", backToSignIn: "Zuruck zur Anmeldung", checkEmail: "Uberprufen Sie Ihre E-Mail", resetLinkSent: "Wir haben einen Passwort-Reset-Link gesendet an" },
    dashboard: { title: "Dashboard", profileSettings: "Profileinstellungen", termsOfService: "Servicebedingungen", privacyPolicy: "Datenschutzrichtlinie", search: "Suchen", balance: "Kontostand", cashflow: "Cashflow", expense: "Ausgabe", bookkeeping: "Buchhaltung", last30Days: "Letzte 30 Tage", addData: "Daten hinzufugen", date: "Datum", type: "Typ", detail: "Detail", price: "Preis", amount: "Betrag", noTransactions: "Noch keine Transaktionen", totalRevenue: "Gesamtumsatz", noDataYet: "Noch keine Daten", goals: "Ziele", addGoal: "Ziel hinzufugen", noGoalsAdded: "Noch keine Ziele hinzugefugt", bankAccount: "Bankkonto", light: "Hell", dark: "Dunkel", version: "Version" },
    settings: {
      languageSettings: "Spracheinstellungen",
      displayLanguage: "Anzeigesprache",
      changeLanguageAcrossSite: "Dies andert die Sprache auf der gesamten Website.",
      notificationSettings: "Benachrichtigungseinstellungen",
      selectNotificationPreference: "Wahlen Sie Ihre Benachrichtigungspräferenz",
      giveFeedback: "Feedback geben",
      logOut: "Abmelden",
      deleteAccount: "Konto loschen",
      deleteAccountWarning: "Das Schließen Ihres Kontos kann nicht rückgängig gemacht werden. Stellen Sie sicher, dass Ihr Kontostand vor Beginn 0,00 USD beträgt.",
      deleteAccountNow: "Konto jetzt loschen",
      languageRegion: "Sprache und Region",
      configureLanguageSettings: "Konfigurieren Sie Ihre bevorzugte Sprache, Zeitzone und regionale Einstellungen",
      timeZone: "Zeitzone",
      selectTimezone: "Zeitzone wahlen",
      currentTime: "Aktuelle Zeit:",
      dateFormat: "Datumsformat",
      today: "Heute:",
      timeFormat: "Zeitformat",
      twelveHour: "12 Stunden (AM/PM)",
      twentyFourHour: "24 Stunden",
      currency: "Wahrung",
      example: "Beispiel:",
      measurementSystem: "Messsystem",
      metric: "Metrisch (kg, cm, L)",
      imperial: "Imperial (lbs, ft, gal)",
      numberFormat: "Zahlenformat",
      regionalPreferences: "Regionale Einstellungen",
      regionSettingsDescription: "Diese Einstellungen helfen, Ihr Erlebnis basierend auf Ihrem Standort und Ihren Präferenzen anzupassen.",
      weekStartsOn: "Woche beginnt am:",
      newsAndUpdates: "Nachrichten und Updates",
      newsAboutProducts: "Nachrichten zu Produkt- und Featureupdates.",
      reminders: "Erinnerungen",
      getRemindersDescription: "Erhalten Sie eine Benachrichtigung, um Sie an Updates zu erinnern, die Sie möglicherweise verpasst haben.",
      pushNotifications: "Push-Benachrichtigungen",
      pushNotificationsDescription: "Erhalten Sie In-App-Benachrichtigungen zu Ihren Ersparnissen und Investitionen.",
      changePhotoProfile: "Profilfoto andern",
      delete: "Loschen",
      save: "Speichern",
      saveChanges: "Anderungen speichern",
      role: "Rolle",
      enterYourRole: "Geben Sie Ihre Rolle ein",
      companyName: "Unternehmensname",
      enterCompanyName: "Unternehmensname eingeben",
      companyEmail: "Unternehmens-E-Mail",
      enterCompanyEmail: "Unternehmens-E-Mail eingeben",
      linkedin: "LinkedIn",
      enterLinkedinUrl: "LinkedIn-URL eingeben",
      dateOfIncorporation: "Gründungsdatum",
      countryOfHeadquartered: "Firmensitz",
      selectACountry: "Wählen Sie ein Land",
      feedbackComingSoon: "Feedbackformular kommt in Kürze.",
      themeSettings: "Designeinstellungen",
      selectAppearance: "Wahlen Sie Ihr bevorzugtes Aussehen",
      lightModeDescription: "Helles Design fur die Verwendung bei Tageslicht",
      darkModeDescription: "Dunkles Design zur Verringerung der Augenbelastung"
    }
  }
};

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (section: string, key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<string>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('finquanta_language');
    if (savedLanguage && translations[savedLanguage]) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: string) => {
    setLanguageState(lang);
    localStorage.setItem('finquanta_language', lang);
  };

  const t = (section: string, key: string): string => {
    return translations[language]?.[section]?.[key] || translations['en']?.[section]?.[key] || `${section}.${key}`;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
