/** Section 11 — Financial Health Score. */

export type RatioKey = 'liquidity' | 'profitability' | 'debtRisk' | 'cashFlow';

export interface Ratio {
  key: RatioKey;
  /** e.g. 'Current Ratio' */
  name: string;
  /** e.g. 'Liquidity' */
  label: string;
  /** The raw ratio. null when it can't be computed (see `note`). */
  value: number | null;
  /** How to render `value`: '1.8×', '12.4%'. */
  format: 'ratio' | 'percent';
  /** 0–100. */
  score: number;
  /** Change in `value` since 30 days ago; null when there's nothing to compare. */
  trend: number | null;
  /** What the ratio measures, in plain language. */
  explanation: string;
  /** What THIS business's number actually means, given its data and profile. */
  insight: string;
  /** Set when the ratio is undefined — e.g. no revenue yet, no liabilities. */
  note?: string;
  /**
   * `insight` and `note` as data. Both are English prose assembled here from the
   * business's own figures, so the client cannot translate the finished string —
   * it needs to know WHICH sentence was chosen and WHICH numbers went into it,
   * then build its own. The English fields above stay for any consumer that
   * hasn't moved over.
   */
  insightParts?: {
    /** Which branch was taken, e.g. 'liqTight'. */
    key: string;
    /** Raw figures the sentence interpolates, unformatted. */
    v?: Record<string, number>;
  };
  noteKey?: string;
}

export interface HealthScore {
  /** False until the business has ~30 days of financial data. */
  ready: boolean;
  /** Days of data recorded so far (first entry → today). */
  daysOfData: number;
  /** Days needed before the first score. */
  daysRequired: number;
  /** 0–100. null while still collecting data. */
  score: number | null;
  /** Change in the overall score since 30 days ago. */
  trend: number | null;
  ratios: Ratio[];
  /** Finna's plain-language summary of the whole picture. English only. */
  summary: string;
  /**
   * The same summary as data, so the client can build the sentence in the
   * reader's language. `summary` above is assembled here by concatenating
   * English fragments ("Your X is the strongest part..."), which no amount of
   * word substitution can translate — word order and grammar differ per
   * language. The client renders from these instead; `summary` stays for any
   * consumer that hasn't moved over.
   */
  summaryParts?: {
    band: 'strong' | 'stable' | 'weak' | 'strained';
    bestKey: RatioKey;
    worstKey: RatioKey;
    /** The weakest area matches the goal they chose at signup. */
    goalAligned: boolean;
  };
  /** The window the profit/cash-flow figures cover. */
  periodDays: number;
}

/** Account balances and flows the ratios are built from. */
export interface FinancialSnapshot {
  cash: number;
  receivables: number;
  loanReceivable: number;
  payables: number;
  loanPayable: number;
  /** Revenue earned in the window (incl. interest income). */
  revenue: number;
  /** Expenses incurred in the window (incl. interest expense). */
  expenses: number;
  /** Cash generated by normal operations — excludes borrowing and lending. */
  operatingCashFlow: number;
}

/** The signup answers that make the insights specific to this business. */
export interface HealthContext {
  maturityStage?: string;
  industry?: string;
  niche?: string;
  hasDebt?: string;
  primaryGoal?: string;
}
