"use client";
import Link from 'next/link';
import { useLanguage } from '@/hooks/context/LanguageContext';

export default function AiRiskDisclosure() {
  const { t } = useLanguage();
  return (
    <main className="min-h-screen bg-white pt-24 pb-16">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-3xl">
        <h1 className="text-2xl font-bold mb-2">{t("legal", "aiRiskTitle")}</h1>
        <p className="text-sm text-gray-500 mb-8">Last Updated: March 20th, 2026</p>
        <p className="text-sm text-gray-700 mb-6">{t("legal", "aiRiskIntro")}</p>

        <h2 className="font-bold mb-2">1. Nature of AI-Generated Insights</h2>
        <p className="text-sm text-gray-700 mb-6">Finquanta's platform may generate financial insights, forecasts, transaction classifications, and analytical reports. These outputs are probabilistic in nature and may not always reflect actual business conditions. Users should manually evaluate AI-generated insights before making financial decisions.</p>
        <h2 className="font-bold mb-2">2. No Financial, Accounting, Tax, or Legal Advice</h2>
        <p className="text-sm text-gray-700 mb-6">Finquanta is a technology platform and not a licensed financial advisor, accounting firm, tax advisor, or legal service provider. Nothing generated by Finquanta should be interpreted as professional advice.</p>
        <h2 className="font-bold mb-2">3. Data Dependency and Accuracy Limitations</h2>
        <p className="text-sm text-gray-700 mb-6">AI systems rely on the quality and accuracy of underlying data. If data provided is incomplete or inaccurate, the resulting analysis may also be inaccurate.</p>
        <h2 className="font-bold mb-2">4. Forecasting and Predictive Limitations</h2>
        <p className="text-sm text-gray-700 mb-6">Financial forecasting inherently involves uncertainty. Actual outcomes may differ significantly from AI-generated projections. Projections should not be interpreted as guarantees of future performance.</p>
        <h2 className="font-bold mb-2">5. Automation Risks</h2>
        <p className="text-sm text-gray-700 mb-6">Automated systems may occasionally produce incorrect categorizations or incomplete records. Users are responsible for periodically reviewing automated outputs.</p>
        <h2 className="font-bold mb-2">6. AI Model Limitations and Bias</h2>
        <p className="text-sm text-gray-700 mb-6">AI models may contain inherent limitations including incomplete understanding of niche industries and potential bias introduced through training data.</p>
        <h2 className="font-bold mb-2">7. User Responsibility</h2>
        <p className="text-sm text-gray-700 mb-6">Users retain full responsibility for maintaining accurate financial records, verifying bookkeeping outputs, and making final financial decisions.</p>
        <h2 className="font-bold mb-2">8. Continuous Improvement of AI Systems</h2>
        <p className="text-sm text-gray-700 mb-10">Finquanta continuously develops and improves its AI models. If you have questions, contact us <a href="mailto:info@finquanta.com" className="underline">here</a>.</p>

        <div className="flex justify-center">
          <Link href="/" className="bg-[#4CAF50] text-white px-8 py-3 rounded-lg font-medium hover:bg-[#45a049]">
            {t("legal", "returnHome")}
          </Link>
        </div>
      </div>
    </main>
  );
}